"TubeInnerDia"= 45'Inner tube Diamiter
"TubeOuterDia"= 50.3'Outer tube dimiter
"TubeLength"= 300'Total length of tube
"FinnHight"= 200'Height of the main tube printed that the fins are mounted to
"FinnRadius"= "FinnHight" - 40'Radius of the fins
"NumOfFins"= 3'Number of fins
"FinnThinkness"= 5'Thickness of the fins
"PhoneWidth"= 80
"PhoneThickness"= 11.5
"OuterDiam"= ( sqr ( ( "PhoneWidth" / 2 ) ^ 2 + ( "PhoneThickness" / 2 ) ) + 3 ) * 2
"PhoneHeight"=150
"ServoLength"= 23
"ServoThickness"= 12
"WireDiamiter"= 2.24
"Clearence"= 0.5
"mountingHoleDiameter"= 2.9
"D1@Sketch1"="TubeOuterDia"+5
"D2@Sketch5"="FinnRadius"
"D1@Boss-Extrude2"="FinnThinkness"/2
"D2@Boss-Extrude2"="FinnThinkness"/2
"D1@Boss-Extrude1"="FinnHight"
